### ISSUE TITLE
The tool does not work on .shtml files

### ISSUE THREAD

**Issue by ghost** [CurbSafeCharmer/refill#11]
same as topic.

**Comment by zhaofengli** [comment]
Could you provide a link as an example?

**Comment by alexanderlime** [comment]
http://bbs.tianya.cn/m/post-no04-2532812-1.shtml

P.S. .asp as well. I'd provide some examples ASAP

**Comment by alexanderlime** [comment]
http://www.land.moi.gov.tw/law/pda/openframe.asp?lid=6202

**Comment by zhaofengli** [comment]
The tianya link works for me, while the gov.tw one failed with "Fetching error" which is unrelated to the file extension. Webpages are technically equal from the client's perspective, whether it's a `.asp` or a `.shtml`.

"Fetching error" means that the program has failed to get the content of the page. It is a long-standing problem which occurs randomly in all kinds of webpages and is hard to debug. This looks like a Labs-specific issue, as the bug is not reproducible locally on my own computer or on a [third-party server](https://reflinks.herokuapp.com/).

**Comment by CurbSafeCharmer** [comment]
As this could not be reproduced, and is so old now, I will close.
